mysql:
  # 测试环境
  dev:
    # 数据账号
    username: "bbs_test_manager"
    # 数据库密码
    password: ""
    # 数据库地址
    Host: ""
    # 数据库端口
    Port: 3306
    # 测试环境数据库的db名
    Dbname: "bbs_test"
  # 生产环境
  prod:
    username: "bbs_test"
    password: ""
    Host: ""
    Port: 3306
    Dbname: "bbs"

redis:
  # 测试环境
  dev:
    addr: ""
    password: ""
    db: 0

  # 生产环境
  prod:

# 运行环境设置
runtimeConfig:
  # 这里会基于 default 的值，根据环境，将对应的环境（dev或者prod）的值合并进去获得最终结果
  # 需要注意的是：假设dev/prod等某个字段有值，但该值为空值，例如int类型值为0，那么最终结果将不会取空值。需要尽量避免这种情况，否则需要特殊设置。
  default:
    # 留空，该变量用于读取运行时的环境变量
    Env: ''
    # 意味着每个接口的路径之前，都需要添加这一段字符串
    BaseUrl: 'bbs/'
    # 在输出日志中添加文件名和方法信息
    SetReportCaller: true
    ServerName: '论坛服务'
    ServerURL: ''
    # 日志最大保留时间（天）
    LogMaxAge: 14
    # 日志切分间隔（小时）
    LogRotationTime: 24
    # 日志显示级别： （参照 logrus.go 文件的 ParseLevel 函数）
    #            panic 极为严重错误
    #            fatal 表示发生了严重的错误，导致程序无法继续运行，
    #            error 表示发生了错误，但程序仍然可以继续运行
    #            warn warning 表示发生了潜在的问题，可能会导致错误
    #            info 表示正常的程序操作信息，
    #            debug 表示详细的调试信息，通常仅在开发和调试过程中使用
    #            trace 表示更详细的调试信息，比 Debug 级别更详细
    LogLevel: "info"
    # 创建第一个超级管理员用户，默认是不创建的。用户名默认是 admin，密码是 12345678
    CreateFirstAdmin: false
    # 不设置时，默认为 admin，以下三条配置的未配置选项，在代码里已硬写死
    # 注意：长度限制为 4~20，否则无法登陆。如需要更改，请自行更改校验相关逻辑
    FirstAdminAccount: "admin"
    # 不设置时，默认值为 超级管理员
    FirstAdminName: "超级管理员"
    # 不设置时，默认为12345678
    # 注意：长度限制为 6~40，否则无法登陆。如需要更改，请自行更改校验相关逻辑
    FirstAdminPassword: "12345678"
    # 新账号注册后，需要管理员审批后才能登录。当值为true时，代表必须管理员审批通过后才能登录
    RegistrationRequiresAdminApproval: false
  dev:
    Env: 'DEV'
    LogLevel: "debug"
    CreateFirstAdmin: true
  prod:
    Env: 'PROD'

commonConfig: # 通用变量，不区分环境
  # 密码加盐用的哈希值，我随便写的。正式运行后，请勿丢失……不然集体登录失败……
  PasswordSalt: "vavewv231er34ggv12fv"
  # 密码 hash 后的长度，不应该超过 BBSUser.Password 的最大长度，否则会导致出错。
  # 这个值的上下限是 8 ~ 64，超出会设置为对应的上下限
  PasswordLengthAfterHash: 40
  # bbs的token字段名
  HeaderTokenName: "bbs-token"
  # 登录过期时间（单位：小时），168小时表示7天。如果不设置或者设置为0，则默认为7天
  LoginExpireTime: 168